head:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - right_thumb_abd_joint
      - right_thumb_inner_joint
      - right_thumb_outer1_joint
      - right_thumb_outer2_joint
      - right_index_abd_joint
      - right_index_inner_joint
      - right_index_outer1_joint
      - right_index_outer2_joint
      - right_middle_abd_joint
      - right_middle_inner_joint
      - right_middle_outer1_joint
      - right_middle_outer2_joint
      - right_ring_abd_joint
      - right_ring_inner_joint
      - right_ring_outer1_joint
      - right_ring_outer2_joint
      - right_pinky_abd_joint
      - right_pinky_inner_joint
      - right_pinky_outer1_joint
      - right_pinky_outer2_joint


    gains: 
      right_thumb_abd_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_thumb_inner_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_thumb_outer1_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_thumb_outer2_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_index_abd_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_index_inner_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_index_outer1_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_index_outer2_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_middle_abd_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_middle_inner_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_middle_outer1_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_middle_outer2_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_ring_abd_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_ring_inner_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_ring_outer1_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_ring_outer2_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_pinky_abd_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_pinky_inner_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_pinky_outer1_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_pinky_outer2_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}

  joint_trajectory_effort_controller: 
    type: "effort_controllers/JointTrajectoryController"
    joints: 
      - right_thumb_abd_joint
      - right_thumb_inner_joint
      - right_thumb_outer1_joint
      - right_thumb_outer2_joint
      - right_index_abd_joint
      - right_index_inner_joint
      - right_index_outer1_joint
      - right_index_outer2_joint
      - right_middle_abd_joint
      - right_middle_inner_joint
      - right_middle_outer1_joint
      - right_middle_outer2_joint
      - right_ring_abd_joint
      - right_ring_inner_joint
      - right_ring_outer1_joint
      - right_ring_outer2_joint
      - right_pinky_abd_joint
      - right_pinky_inner_joint
      - right_pinky_outer1_joint
      - right_pinky_outer2_joint

    gains: # Required because we're controlling an effort interface
      right_thumb_abd_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_thumb_inner_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_thumb_outer1_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_thumb_outer2_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_index_abd_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_index_inner_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_index_outer1_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_index_outer2_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_middle_abd_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_middle_inner_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_middle_outer1_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_middle_outer2_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_ring_abd_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_ring_inner_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_ring_outer1_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_ring_outer2_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_pinky_abd_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_pinky_inner_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_pinky_outer1_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}
      right_pinky_outer2_joint: {p: 100.0,  d: 10.0, i: 0.1, i_clamp: 1}

  # Position Controllers ---------------------------------------
  right_thumb_abd_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_thumb_abd_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_thumb_inner_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_thumb_inner_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_thumb_outer1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_thumb_outer1_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_thumb_outer2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_thumb_outer2_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_index_abd_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_index_abd_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_index_inner_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_index_inner_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_index_outer1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_index_outer1_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_index_outer2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_index_outer2_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_middle_abd_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_middle_abd_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_middle_inner_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_middle_inner_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_middle_outer1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_middle_outer1_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_middle_outer2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_middle_outer2_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_ring_abd_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_ring_abd_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_ring_inner_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_ring_inner_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_ring_outer1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_ring_outer1_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_ring_outer2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_ring_outer2_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_pinky_abd_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_pinky_abd_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_pinky_inner_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_pinky_inner_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_pinky_outer1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_pinky_outer1_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  right_pinky_outer2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_pinky_outer2_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

    